version: '3.8'

services:
  app:
    build: .
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=production
      - JKOPAY_API_URL=https://gateway.suntone.com/payment/api/gotoPayment
      - JKOPAY_MERCHANT_ID=1888
      - JKOPAY_TERMINAL_ID=888506
      - JKOPAY_SECRET_KEY=fe5b2c5ea084426bb1f6269acbac902f
      - JKOPAY_RETURN_URL=https://jinshiying.com/payment/return
      - JKOPAY_NOTIFY_URL=https://jinshiying.com/api/payment/notify
      - NEXT_PUBLIC_BASE_URL=https://jinshiying.com
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fengshui_ecommerce
      - POSTGRES_USER=fengshui_user
      - POSTGRES_PASSWORD=your_secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
